`timescale 1ns / 1ps
// ==========================================================================
// Module: mux
// Generated by Tools HDL
// ==========================================================================
module mux #(parameter WIDTH = 32)(
    input   logic [WIDTH-1:0]         in0,
    input   logic [WIDTH-1:0]         in1,
    input   logic                     sel,
    output  logic [WIDTH-1:0]         out
);

    assign out = sel ? in1 : in0;
endmodule