`timescale 1ns / 1ps
// ==========================================================================
// Module: ControlUnit
// Generated by Tools HDL
// ==========================================================================
import alu_pkg::*;
import op_codes_pkg::*;


module convertAlu_ctr(
    output  logic  [3:0]   alu_ctrl, // ALU_ADD, ALU_SUB, ALU_AND ...
    
    input   logic  [2:0] funct3, 
    input   logic  [6:0] funct7,
    input   logic  [6:0] opcode
);

    always_comb begin
        case (funct3)
            3'b000 :  
                case(opcode)
                    OP_IMM  : alu_ctrl = ALU_ADD;
                    default :
                    case(funct7) 
                            7'b0000000:  alu_ctrl = ALU_ADD;
                            7'b0100000:  alu_ctrl = ALU_SUB;
                            default   :  alu_ctrl = ALU_ERR;
                    endcase
                endcase
            3'b001 :  alu_ctrl = ALU_SLL;
            3'b010 :  alu_ctrl = ALU_SLT;
            3'b011 :  alu_ctrl = ALU_SLTU;
            3'b100 :  alu_ctrl = ALU_XOR;
            3'b101 : 
                case(funct7) 
                        7'b0000000:  alu_ctrl = ALU_SRL;
                        7'b0100000:  alu_ctrl = ALU_SRA;
                        default   :  alu_ctrl = ALU_ERR;
                endcase
            3'b110 :  alu_ctrl = ALU_OR;
            3'b111 :  alu_ctrl = ALU_AND;
            default:  alu_ctrl = ALU_ERR;
        endcase
    end
    
endmodule

// regWrite | ALU_src | MemWrite | MemToReg | PCsrc

module ControlUnit (
    input   logic  [31:0]  instruction,
    output  logic          regWrite,
    output  logic          ALU_src,  // op2 source : 0 => reg.out(rs2), 1 => immm 
    output  alu_op_t       alu_ctrl, // ALU_ADD, ALU_SUB, ALU_AND ...
    output  logic          MemWrite, 
    output  logic          MemSrc,   // mem.in : 0 => rs2, 1 => imm
    output  logic          MemToReg, // reg.input : 0 => alu(out), 1 => mem.out
    output  logic          PCsrc     // pc.in : 0 => alu.out, 1 => imm
);
    logic  [6:0] OpCode;
    logic  [4:0] rd;
    logic  [4:0] rs1;
    logic  [4:0] rs2;
    logic  [2:0] funct3; 
    logic  [6:0] funct7;
    logic  [31:0] imm;
    format_t format;

    decoder dec (
        .instruction (instruction),
        .OpCode      (OpCode),
        .rd          (rd),
        .rs1         (rs1),
        .rs2         (rs2),
        .funct3      (funct3),
        .funct7      (funct7),
        .imm         (imm)
    );

    // convert to aluctrl :
    convertAlu_ctr conv(
        .alu_ctrl(alu_ctrl),
        .funct3(funct3), 
        .funct7(funct7),
        .opcode(OpCode)
    );

    decoder_format form (
        .instruction(instruction),
        .format(format)
    );


    always_comb begin
        // default values 
        regWrite  = '0;
        ALU_src   = '0;
        // alu_ctrl  = ALU_ERR;
        MemWrite  = '0;
        MemSrc    = '0; // not used for now, for hazard unit 
        MemToReg  = '0; 
        PCsrc     = '0;

        // signal by signal: 
        // regwrite
        // regWrite = rd == '0 ? '0 : '1;
        // case (format)This don't take into account the OP_MISCMEM and OP_SYS
        //     TYPE_R, TYPE_I, TYPE_U, TYPE_J  : regWrite = '1;
        // endcase
        case (OpCode)
            OP_LOAD, OP_JALR, OP_JAL, OP_IMM, OP_REG, OP_AUIPC,OP_LUI : regWrite = '1;
        endcase
        

        // Alu Src
        // case (format) This don't take into account the OP_MISCMEM and OP_SYS
        //     TYPE_I, TYPE_U  : ALU_src = '1;
        // endcase
        case (OpCode)
            OP_LOAD, OP_STORE, OP_JALR, OP_IMM, OP_AUIPC,OP_LUI : ALU_src = '1;
        endcase

        // MemWrite
        case (OpCode)
            OP_STORE : MemWrite = '1;
        endcase

        // MemToReg
        case (OpCode)
            OP_LOAD : MemToReg = '1;
        endcase

        // PCsrc
        case (OpCode)
            OP_JALR, OP_JAL, OP_BRANCH : PCsrc = '1;
        endcase
    end
endmodule