`timescale 1ns / 1ps


typedef enum logic [2:0] {
    TYPE_R,
    TYPE_I,
    TYPE_S,
    TYPE_B,
    TYPE_U,
    TYPE_J,
    TYPE_UNKNOWN
} format_t;

// Opcodes standards RV32I (bits [6:2], ou [6:0] si vous incluez les bits bas '11')
localparam [6:0] OP_LOAD   = 7'b0000011; // Type I (ex: lb, lh, lw)
localparam [6:0] OP_STORE  = 7'b0100011; // Type S (ex: sb, sh, sw)

localparam [6:0] OP_BRANCH = 7'b1100011; // Type B (ex: beq, bne, blt)

localparam [6:0] OP_JALR   = 7'b1100111; // Type I 
localparam [6:0] OP_JAL    = 7'b1101111; // Type J

localparam [6:0] OP_IMM    = 7'b0010011; // Type I (ex: ADDI, ANDI...)
localparam [6:0] OP_REG    = 7'b0110011; // Type R (ex: ADD, SUB, OR...)

localparam [6:0] OP_AUIPC  = 7'b0010111; // Type U
localparam [6:0] OP_LUI    = 7'b0110111; // Type U

localparam [6:0] OP_MISCMEM= 7'b0001111; // Type I (ex: ecall, ebreak)
localparam [6:0] OP_SYS    = 7'b1110011; // Type I (ex: fence)


// ==========================================================================
// Module: decoder
// Generated by SystemVerilog Tool
// ==========================================================================

module decoder_format (
        input   logic  [31:0]  instruction,
        output format_t format
);
    logic [6:0] OpCode;
    assign OpCode =  instruction[6:0];
    always_comb begin
        case (OpCode) 
            OP_REG:    format = TYPE_R;
            
            OP_IMM, 
            OP_LOAD,
            OP_SYS,
            OP_MISCMEM, 
            OP_JALR:   format = TYPE_I;
            
            OP_STORE:  format = TYPE_S;
            
            OP_BRANCH: format = TYPE_B;
            
            OP_LUI, 
            OP_AUIPC:  format = TYPE_U;
            
            OP_JAL:    format = TYPE_J;
            
            default:   format = TYPE_UNKNOWN; // Gestion des opcodes invalid;
        endcase
    end
    
endmodule
module decoder (
    input   logic  [31:0]  instruction,
    output  logic  [6:0]   OpCode,
    output  logic  [4:0]   rd,
    output  logic  [4:0]   rs1,
    output  logic  [4:0]   rs2,
    output  logic  [2:0]   funct3,
    output  logic  [6:0]   funct7,
    output  logic  [31:0]  imm
);

    format_t format;

    decoder_format dec (
        .instruction(instruction),
        .format(format)
    );

    assign OpCode =  instruction[6:0];

    always_comb begin 
        // Default assignments prevent inferred latches and satisfy the testbench
        rd     = '0;
        rs1    = '0;
        rs2    = '0;
        funct3 = '0;
        funct7 = '0;
        imm    = '0;

        case (format)
            TYPE_R: begin
                rd     = instruction[11:7];
                rs1    = instruction[19:15];
                rs2    = instruction[24:20];
                funct3 = instruction[14:12];
                funct7 = instruction[31:25];
            end
            TYPE_I: begin
                rd     = instruction[11:7];
                rs1    = instruction[19:15];
                funct3 = instruction[14:12];
                imm    = {{20{instruction[31]}}, instruction[31:20]};
            end
            TYPE_S: begin
                rs1    = instruction[19:15];
                rs2    = instruction[24:20];
                funct3 = instruction[14:12];
                imm    = {{20{instruction[31]}}, instruction[31:25], instruction[11:7]};
            end
            TYPE_B: begin
                rs1    = instruction[19:15];
                rs2    = instruction[24:20];
                funct3 = instruction[14:12];
                imm    = {{20{instruction[31]}}, instruction[7], instruction[30:25], instruction[11:8], 1'b0};
            end
            TYPE_U: begin
                rd     = instruction[11:7];
                imm    = {instruction[31:12], 12'b0};
            end
            TYPE_J: begin
                rd     = instruction[11:7];
                imm    = {{12{instruction[31]}}, instruction[19:12], instruction[20], instruction[30:21], 1'b0};
            end
            default: ;
        endcase
    end
endmodule