`timescale 1ns / 1ps





// ==========================================================================
// Module: decoder
// Generated by SystemVerilog Tool
// ==========================================================================
import op_codes_pkg::*;

module decoder_format (
        input   logic  [31:0]  instruction,
        output format_t format
);
    logic [6:0] OpCode;
    assign OpCode =  instruction[6:0];
    always_comb begin
        case (OpCode) 
            OP_REG:    format = TYPE_R;
            
            OP_IMM, 
            OP_LOAD,
            OP_SYS,
            OP_MISCMEM, 
            OP_JALR:   format = TYPE_I;
            
            OP_STORE:  format = TYPE_S;
            
            OP_BRANCH: format = TYPE_B;
            
            OP_LUI, 
            OP_AUIPC:  format = TYPE_U;
            
            OP_JAL:    format = TYPE_J;
            
            default:   format = TYPE_UNKNOWN; // Gestion des opcodes invalid;
        endcase
    end
    
endmodule
module decoder (
    input   logic  [31:0]  instruction,
    output  logic  [6:0]   OpCode,
    output  logic  [4:0]   rd,
    output  logic  [4:0]   rs1,
    output  logic  [4:0]   rs2,
    output  logic  [2:0]   funct3,
    output  logic  [6:0]   funct7,
    output  logic  [31:0]  imm
);

    format_t format;

    decoder_format dec (
        .instruction(instruction),
        .format(format)
    );

    assign OpCode =  instruction[6:0];

    always_comb begin 
        // Default assignments prevent inferred latches and satisfy the testbench
        rd     = '0;
        rs1    = '0;
        rs2    = '0;
        funct3 = '0;
        funct7 = '0;
        imm    = '0;

        case (format)
            TYPE_R: begin
                rd     = instruction[11:7];
                rs1    = instruction[19:15];
                rs2    = instruction[24:20];
                funct3 = instruction[14:12];
                funct7 = instruction[31:25];
            end
            TYPE_I: begin
                rd     = instruction[11:7];
                rs1    = instruction[19:15];
                funct3 = instruction[14:12];
                funct7 = instruction[31:25];
                imm    = {{20{instruction[31]}}, instruction[31:20]};
            end
            TYPE_S: begin
                rs1    = instruction[19:15];
                rs2    = instruction[24:20];
                funct3 = instruction[14:12];
                imm    = {{20{instruction[31]}}, instruction[31:25], instruction[11:7]};
            end
            TYPE_B: begin
                rs1    = instruction[19:15];
                rs2    = instruction[24:20];
                funct3 = instruction[14:12];
                imm    = {{20{instruction[31]}}, instruction[7], instruction[30:25], instruction[11:8], 1'b0};
            end
            TYPE_U: begin
                rd     = instruction[11:7];
                imm    = {instruction[31:12], 12'b0};
            end
            TYPE_J: begin
                rd     = instruction[11:7];
                imm    = {{12{instruction[31]}}, instruction[19:12], instruction[20], instruction[30:21], 1'b0};
            end
            default: ;
        endcase
    end
endmodule