`timescale 1ns / 1ps
// ==========================================================================
// Module: top
// Generated by Tools HDL
// ==========================================================================
module top #(
    parameter PROG_FILE = "programms/default.txt"
)(
    input   logic          clk,
    input   logic          rst
);
    
    logic [31:0] pc_new_pc;
    logic        pc_override;
    logic [31:0] pc_pc;
    pc pc (
        .clk      (clk),
        .rst      (rst),
        .new_pc   (pc_new_pc),
        .override (pc_override),
        .pc       (pc_pc)
    );

    logic [31:0] rom_pc;
    logic [31:0] rom_out;
    rom #(
            .PROG_FILE(PROG_FILE) 
     ) rom (
        .pc  (rom_pc),
        .clk (clk),
        .rst (rst),
        .out (rom_out)
    );

    logic [31:0] cu_instruction;
    logic        cu_regWrite;
    logic        cu_ALU_src;
    alu_op_t     cu_alu_ctrl;
    logic        cu_MemWrite;
    logic        cu_MemSrc;
    logic        cu_MemToReg;
    logic        cu_PCsrc;
    ControlUnit cu (
        .instruction (cu_instruction),
        .regWrite    (cu_regWrite),
        .ALU_src     (cu_ALU_src),
        .alu_ctrl    (cu_alu_ctrl),
        .MemWrite    (cu_MemWrite),
        .MemSrc      (cu_MemSrc),
        .MemToReg    (cu_MemToReg),
        .PCsrc       (cu_PCsrc)
    );


    logic [31:0] alu_in1;
    logic [31:0] alu_in2;
    alu_op_t     alu_alu_ctrl;
    logic [31:0] alu_out;
    logic        alu_zero;
    alu alu (
        .in1        (alu_in1),
        .in2        (alu_in2),
        .alu_ctrl   (alu_alu_ctrl),
        .out        (alu_out),
        .zero       (alu_zero)
    );
    
    logic [31:0] dec_instruction;
    logic [6:0]  dec_OpCode;
    logic [4:0]  dec_rd;
    logic [4:0]  dec_rs1;
    logic [4:0]  dec_rs2;
    logic [2:0]  dec_funct3;
    logic [6:0]  dec_funct7;
    logic [31:0] dec_imm;
    decoder dec (
        .instruction (dec_instruction),
        .OpCode      (dec_OpCode),
        .rd          (dec_rd),
        .rs1         (dec_rs1),
        .rs2         (dec_rs2),
        .funct3      (dec_funct3),
        .funct7      (dec_funct7),
        .imm         (dec_imm)
    );

    logic [31:0] regs_in;
    logic [31:0] regs_out1;
    logic [31:0] regs_out2;
    logic [4:0]  regs_rd;
    logic [4:0]  regs_rs1;
    logic [4:0]  regs_rs2;
    logic        regs_RegWrite;
    RegFile regs (
        .in       (regs_in),
        .out1     (regs_out1),
        .out2     (regs_out2),
        .rd       (regs_rd),
        .rs1      (regs_rs1),
        .rs2      (regs_rs2),
        .RegWrite (regs_RegWrite),
        .clk      (clk),
        .rst      (rst)
    );


    logic [31:0] mux_alu_src_in0;
    logic [31:0] mux_alu_src_in1;
    logic        mux_alu_src_sel;
    logic [31:0] mux_alu_src_out;

    mux #(.WIDTH(32)) mux_alu_src (
        .in0 (mux_alu_src_in0),
        .in1 (mux_alu_src_in1),
        .sel (mux_alu_src_sel),
        .out (mux_alu_src_out)
    );

    logic [31:0] mux_mem_reg_in0;
    logic [31:0] mux_mem_reg_in1;
    logic        mux_mem_reg_sel;
    logic [31:0] mux_mem_reg_out;

    mux #(.WIDTH(32)) mux_mem_reg (
        .in0 (mux_mem_reg_in0),
        .in1 (mux_mem_reg_in1),
        .sel (mux_mem_reg_sel),
        .out (mux_mem_reg_out)
    );

    logic [15:0]  singExt_in;
    logic [31:0]  singExt_out;

    signExtender singExt (
        .in  (singExt_in),
        .out (singExt_out)
    );

    always_comb begin
        // rom input
        rom_pc = pc_pc;
        
        // decoder input
        dec_instruction = rom_out;
        // Control unit input
        cu_instruction = rom_out;

        // registerfile input
        regs_rs1 = dec_rs1;
        regs_rs2 = dec_rs2;
        regs_rd  = dec_rd;
        regs_in  = mux_mem_reg_out;
        regs_RegWrite = cu_regWrite;

        //sing extender input
        singExt_in = dec_imm;

        // mux alu src input
        mux_alu_src_in0 = regs_out2;
        mux_alu_src_in1 = singExt_out;
        mux_alu_src_sel = cu_ALU_src;
        
        // alu input
        alu_in1 = regs_out1;
        alu_in2 = mux_alu_src_out;
        alu_alu_ctrl = cu_alu_ctrl;

        // mux mem reg input
        mux_mem_reg_in0 = alu_out;
        // mux_mem_reg_in1 = data_mem_out;
        mux_mem_reg_in1 = '1;
        mux_mem_reg_sel = cu_MemToReg;

    end


    
endmodule